[package]
name = "empty"
version = "0.1.0"
edition = "2021"

[build-dependencies]
cdylib-link-lines = "0.1"

[dependencies]
dynamorio-rs = { git = "https://github.com/StephanvanSchaik/dynamorio-rs" }
