name: Clippy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    toolchain: nightly

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Run clippy
      run: cargo clippy
