name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Build drstd
      run: cargo build --verbose --package drstd
    - name: Build dynamorio-rs
      run: cargo build --verbose --package dynamorio-rs
    - name: Build libempty.so
      run: cargo build --verbose --package empty
    - name: Build libstrace.so
      run: cargo build --verbose --package strace
